<?php
/**
 * @category    enrichment-progress
 * @date        20/09/2018 13:46
 * @author      Korneliusz Kirsz <kkirsz@divante.co>
 * @copyright   Copyright (c) 2018 Divante Ltd. (https://divante.co/)
 */

namespace EnrichmentProgressBundle\Data;

use Pimcore\Model\DataObject\ClassDefinition\Data\CalculatedValue;

class EnrichmentProgress extends CalculatedValue
{
    /**
     * @var string
     */
    public $fieldtype = 'enrichmentProgress';

    /**
     * @var string
     */
    public $queryColumnType = 'tinyint';

    public function __construct()
    {
        parent::setCalculatorClass(EnrichmentProgressCalculator::class);
    }

    /**
     * @return string
     */
    public function getQueryColumnType()
    {
        return $this->queryColumnType;
    }

    public function setCalculatorClass($calculatorClass)
    {
        return;
    }

    /**
     * @param mixed $data
     * @param mixed $object
     * @param array $params
     * @return mixed
     */
    public function getDataForGrid($data, $object = null, $params = [])
    {
        if (is_numeric($data)) {
            return $data / 100;
        }

        return null;
    }

    public function getDataForEditmode($data, $object = null, $params = [])
    {
        return parent::getDataForEditmode($data, $object, $params) . "%"; // TODO: Change the autogenerated stub
    }
}
